In [4]:
import import_ipynb

from Job import Job
from Vehicle import Vehicle

In [3]:

import importlib
import numpy as np
from typing import Dict, Tuple, Sequence, List, Any
import matplotlib.pyplot as plt
import folium
import pandas as pd 
import datetime
import types
import requests

from typing import Dict, Tuple, Sequence, List, Any
import polyline

import json

import pprint

 
import os
import pymysql
import pandas as pd

In [4]:
        from IPython.core.display import display, HTML
        display(HTML("""
        <style>
        #notebook-container {
            width: 100%
        }

        .code_cell {
           flex-direction: row !important;
        }

        .code_cell .input {
            width: 50%
        }

        .code_cell .output_wrapper {
            width: 50%
        }
        </style>
        """))

In [9]:
fullDataFrame = pd.read_csv("id3.csv")
date = "20200204"
# # fullDataFrame = fullDataFrame.loc[(fullDataFrame['Courier Type'] != "NON_GCA5") ]

# # fullDataFrame = fullDataFrame.loc[(fullDataFrame["Courier Type"] == "NON_GCA5" )]
# fullDataFrame = fullDataFrame['awb_booking'].astype(str)
# partialDataFrame = fullDataFrame.loc[fullDataFrame['Act Dt'] == int(date)]
# # partialDataFrame

# fullDataFrame.rename( columns={'Unnamed: 0':'new column name'}, inplace=True )

# test = fullDataFrame.loc[fullDataFrame['new column name'] == 0]
# test
# # partialDataFrame.to_csv("partial.csv")
# # partialDataFrame.iloc[0]
# # fullDataFrame.iloc[0]

# row = test.iloc[0]

fullDataFrame.index[0]

0

In [11]:
a = [1,1,3]
countArraySearched = a.count(1)
countArraySearched

2

In [59]:
def getRouteIndexWithID(readed : dict, jobID :id)-> dict:
    for indexRoute, routes in enumerate( readed["routes"] , start = 0): 
        for indexStep, step in enumerate( routes["steps"], start = 1):
                if(step["type"] == "job"):
                    if(step["job"] == jobID):
                        return indexStep, indexRoute
    
    return [],[]
#     return 1,2,indexRoute

def getLocationsAscendingFromRoute(routes : dict, index :int):
    locations = []
    for step in routes["steps"]:
        locations.append(step["location"])
    return locations

def getRouteDetailWithID(ID):
    readed = getResponseFileAsDict()    
    indexStep, indexRoute = getRouteIndexWithID(readed, ID)
    if(indexStep == [] or indexRoute == []) :
        return [],[],[]
    else:
        locations = getLocationsAscendingFromRoute(readed["routes"][indexRoute], indexStep)
        idLocation = locations[indexStep]
        vehicleID = getRouteVehicleID(readed["routes"], indexRoute)

        return readed["routes"][indexRoute], indexStep, vehicleID

def getRouteVehicleID(routes, index):
    return routes[index]["vehicle"]

new column name           0
PUD Svc Area            KUL
PUD Fac                 EAC
PUD Rte                ACA1
PUD Cycle                 B
Courier id         rafinord
Courier Type            NaN
Customer Name           NaN
Street                  NaN
zip                     NaN
City                    NaN
Act Dt             20200201
Act Base                NaN
Delivery Type           NaN
Pickup Type             NaN
Prod Grp                NaN
Prod Code               NaN
ShpCnt                  NaN
Pallets Pcs             NaN
Parcel Pcs              NaN
Total Pcs               NaN
Weight                  NaN
AR dtm                  NaN
Act Tm                 9:20
Open                    NaN
Closed                  NaN
lat                     NaN
lgtd                    NaN
awb_booking             NaN
Act Ckpt Code         DEPAR
PuD Type                NaN
Stop Code               NaN
MarkerColor             NaN
Name: 0, dtype: object

In [81]:
fullDataFrame
fullDataFrame = fullDataFrame[["Courier id", "zip"]]
fullDataFrame = fullDataFrame[fullDataFrame['zip'].notna()]


fullDataFrame = fullDataFrame[fullDataFrame["zip"].astype(str).str.isdigit()] 


test = fullDataFrame.groupby(["Courier id"])["zip"].aggregate(lambda x: set(map(int, x)))
test

print(test["amohdol"])

{71010, 63000, 71050, 42700, 71950, 70000, 43800, 70200, 71450, 70300}

In [82]:
fullDataFrame = pd.read_csv("1.csv")

fullDataFrame = fullDataFrame.loc[(fullDataFrame['Courier Type'] != "NON_GCA5") ]


fullDataFrame["id"] = fullDataFrame.index+1
fullDataFrame

,PUD Svc Area,PUD Fac,PUD Rte,PUD Cycle,Courier id,Courier Type,Customer Name,Street,zip,City,...,Open,Closed,lat,lgtd,awb_booking,Act Ckpt Code,PuD Type,Stop Code,MarkerColor,id
0,KUL,EAC,ACA1,B,rafinord,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,DEPAR,NaN,NaN,NaN,1
1,KUL,EAC,ACA1,B,rafinord,DHL Courier,DHL EXPRESS M SDN BHD,"LOT PT 13757,JALAN HARUAN 1\nOAKLAND INDUSTRIA...",70300,SEREMBAN,...,NaN,23:59,NaN,NaN,7511555413,OK,DL,1.0,NaN,2
2,KUL,EAC,ACA1,B,rafinord,DHL Courier,THIAM YEW CHUA,"249, JALAN 9, TAMAN BUKIT GALENA\nN/A\nSEREMBAN",70200,SEREMBAN,...,NaN,23:59,2.729141,101.908920,8402377443,OK,DL,2.0,NaN,3
3,KUL,EAC,ACA1,B,rafinord,DHL Courier,FG FAMILY GOLD,"NO.113, JLN KESUMA 4B / 1\nBDR TASIK KESUMA 40...",43700,BERANANG,...,9:00,12:00,2.913812,101.872085,6224210694,PU,PU,1.0,NaN,4
4,KUL,EAC,ACA1,B,rafinord,DHL Courier,MANDY LEE,30 JALAN KESUMA 7/5\nBANDAR TASIK KESUMA SELAN...,43700,BERANANG,...,NaN,23:59,2.898578,101.871412,4757007743,OK,DL,3.0,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7603,KUL,EAC,ACQ2,B,ravenda,Service Partner,BAERLOCHER M TRADING AND SERVICES,SDN BHD. LOT 635 & 660 KAWASAN\nPERINDUSTRIAN ...,71450,SEREMBAN,...,NaN,NaN,2.678117,102.004406,4106272435,PU,PU,3.0,NaN,7604
7604,KUL,EAC,ACQ2,B,ravenda,Service Partner,EXIS TECH SDN BHD,"LOT 26209, JALAN TJ 2/2\nTUANKU JAFFAR INDUSTR...",71450,SEREMBAN,...,NaN,23:59,2.677906,102.004469,6791721963,OK,DL,4.0,NaN,7605
7605,KUL,EAC,ACQ2,B,ravenda,Service Partner,CPAK CERGAS SDN BHD,LOT 22 JALAN BUNGA TANJUNG\nSENAWANG INDUSTRIA...,70400,SEREMBAN,...,9:30,12:30,2.685681,101.987760,5521357940,PU,PU,4.0,NaN,7606
7606,KUL,EAC,ACQ2,B,ravenda,Service Partner,VS FAMILIA SDN BHD,"LOT 71&72, JALAN PERNIAGAAN SENAWANG 1 TAMAN P...",70450,SEREMBAN,...,0:00,12:00,2.695789,101.967709,002918 - 550456849,FP,FP,1.0,NaN,7607
7607,KUL,EAC,ACQ2,B,ravenda,Service Partner,NaN,NaN,NaN,NaN,...,NaN,23:59,2.704715,101.916464,NaN,ARRVD,NaN,NaN,NaN,7608

<class 'set'>
{'71050', '70200', '70000', '42700', '71950', '70300', '71010', '63000', '43800', '71450'}
['71050', '70200', '70000', '42700', '71950', '70300', '71010', '63000', '43800', '71450']
['71050', '70200', '70000', '42700', '71950', '70300', '71010', '63000', '43800', '71450', 1]

NameError: name 'test2' is not defined

                       Act Dt  ShpCnt  Pallets Pcs  Parcel Pcs  Total Pcs  \
Courier id zip
amohdol    42700    505005287    45.0          1.0         6.0       48.0
           43800     60600646    36.0          0.0         0.0       36.0
           63000    383804332    32.0          0.0         1.0       32.0
           70000     20200210     1.0          0.0         1.0        1.0
           70200    929209870    77.0          2.0        39.0      104.0
...                       ...     ...          ...         ...        ...
subrniam   71800  24018056452  2253.0        107.0      1176.0     2724.0
           71807    585806252    67.0          7.0        54.0       89.0
           71809    141401547    11.0          0.0        47.0       54.0
           71900     40400428     2.0          0.0         1.0        2.0
           9000      40400437     4.0          0.0         2.0        4.0

                     Weight          lat           lgtd  Stop Code  \
Courier id zip
amohdol    42700    185.250    70.645254    2540.172673       93.0
           43800     25.370     8.591013     304.916279        8.0
           63000     20.110    55.576399    1931.524554      112.0
           70000      4.450     2.672975     101.859613       23.0
           70200    417.021   124.249203    4687.805327      327.0
...                     ...          ...            ...        ...
subrniam   71800  10776.145  3353.527387  120340.551216    17961.0
           71807    673.360    81.687714    2952.437666      378.0
           71809    289.980    19.787120     712.731624       74.0
           71900      3.620     5.444470     203.772146       34.0
           9000       2.260     5.678688     203.651011        8.0

                  MarkerColor
Courier id zip
amohdol    42700          0.0
           43800          0.0
           63000          0.0
           70000          0.0
           70200          0.0
...                       ...
subrniam   71800          0.0
           71807          0.0
           71809          0.0
           71900          0.0
           9000           0.0

[192 rows x 10 columns]